name: morphy_annotation
description: annotation for morphy which provides a clean class definition with extra functionality including; copy with, json serializable, tostring, equals that supports inheritance and polymorphism
version: 1.4.2+2
homepage: https://github.com/atreeon/morphy

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  dartx: ^1.2.0
  json_annotation: ^4.9.0
  quiver: ^3.2.2

dev_dependencies:
  test: ^1.26.3